group=Ryukazan
name=Economy
version=1.0.1
java_version=25
mod_description=Adds a money value saved to players and economy commands.
website=yigitguven.net
server_version=*
game_build=latest
entry_point=com.yigit.economy.Main

# NOTE: Users cloning this repo should set hytaleHome in their local system environment
hytaleHome=C:/Users/yigit/AppData/Roaming/Hytale/install
patchline=release